//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMC.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ButterTable
    {
        public int ButterID { get; set; }
        public int UnitOfMeasuresID { get; set; }
        public int TypeID { get; set; }
        public string Quantity { get; set; }
        public int DepartmentID { get; set; }
        public string DateProduction { get; set; }
        public int StatuseID { get; set; }
    
        public virtual Typess Typess { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual Department Department { get; set; }
        public virtual Status Status { get; set; }
    }
}
