//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMC.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int UserRole { get; set; }
        public int UserStatus { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> IsShiftActive { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserStatus UserStatus1 { get; set; }
        public virtual Department Department { get; set; }
    }
}
