//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMC.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogID { get; set; }
        public string UserName { get; set; }
        public string ActionType { get; set; }
        public string ActionDescription { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public int UserlogID { get; set; }
        public string Ip { get; set; }
    }
}
